
import 'package:flutter/material.dart';

class Product{
  final String title;
  final String desc;
  final String image;
  final String review;
  final String seller;
  final double price;
  final List<Color> colors;
  final String category;
  final double rate;
   int quantity;

  Product({required this.quantity,required this.title, required this.desc, required this.image, required this.review, required this.seller, required this.price, required this.colors, required this.category, required this.rate});

}
final List<Product> all = [
  Product(quantity: 1,
      title: "Wireless Headphones",
      desc: "Headphones , waterproof , good sound  Headphones , waterproof , good sound Headphones , waterproof , good sound Headphones , waterproof , good sound",
      image: "images/wireless.png",
      review: "(320 Reviews)",
      seller: "Zeyad Abdelglel",
      price: 120,
      colors: [
        Colors.black,
        Colors.blue,
        Colors.orange,
      ],
      category: "Electronics",
      rate: 4.8,
  ),
  Product(quantity: 1,
    title: "Man Jacket",
    desc: "Headphones , waterproof , good sound",
    image: "images/man jacket.png",
    review: "(320 Reviews)",
    seller: "Zeyad Abdelglel",
    price: 120,
    colors: [
      Colors.black,
      Colors.blue,
      Colors.orange,
    ],
    category: "Electronics",
    rate: 4.8,
  ),
  Product(quantity: 1,
    title: "perfume",
    desc: "Headphones , waterproof , good sound",
    image: "images/perfume.png",
    review: "(320 Reviews)",
    seller: "Zeyad Abdelglel",
    price: 120,
    colors: [
      Colors.black,
      Colors.blue,
      Colors.orange,
    ],
    category: "Electronics",
    rate: 4.8,
  ),
  Product(quantity: 1,
    title: "Women T-shirt",
    desc: "Headphones , waterproof , good sound",
    image: "images/t-shert.png",
    review: "(320 Reviews)",
    seller: "Zeyad Abdelglel",
    price: 120,
    colors: [
      Colors.black,
      Colors.blue,
      Colors.orange,
    ],
    category: "Electronics",
    rate: 4.8,
  ),
  Product(quantity: 1,
    title: "vans old school",
    desc: "Headphones , waterproof , good sound",
    image: "images/vans old skool.png",
    review: "(320 Reviews)",
    seller: "Zeyad Abdelglel",
    price: 120,
    colors: [
      Colors.black,
      Colors.blue,
      Colors.orange,
    ],
    category: "Electronics",
    rate: 4.8,
  ),
  Product(quantity: 1,
    title: "Watch",
    desc: "Headphones , waterproof , good sound",
    image: "images/watch.png",
    review: "(320 Reviews)",
    seller: "Zeyad Abdelglel",
    price: 120,
    colors: [
      Colors.black,
      Colors.blue,
      Colors.orange,
    ],
    category: "Electronics",
    rate: 4.8,
  ),
  Product(quantity: 1,
    title: "Wireless Headphones",
    desc: "Headphones , waterproof , good sound",
    image: "images/wireless.png",
    review: "(320 Reviews)",
    seller: "Zeyad Abdelglel",
    price: 120,
    colors: [
      Colors.black,
      Colors.blue,
      Colors.orange,
    ],
    category: "Electronics",
    rate: 4.8,
  ),
  Product(quantity: 1,
    title: "vans old school",
    desc: "Headphones , waterproof , good sound",
    image: "images/vans old skool.png",
    review: "(320 Reviews)",
    seller: "Zeyad Abdelglel",
    price: 120,
    colors: [
      Colors.black,
      Colors.blue,
      Colors.orange,
    ],
    category: "Electronics",
    rate: 4.8,
  ),
  Product(
      quantity: 20,
      title: "Air Jordan",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/Air Jordan.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 700,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 20,
      title: "New Balance 990",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/New Balance 990.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 700,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 20,
      title: "Spots shoes",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/shoes.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 700,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 20,
      title: "New Sports shoes",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/sports shoes.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 700,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 20,
      title: "face care",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/face care.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 500,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 20,
      title: "Perfume",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/perfume.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 500,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 20,
      title: "man jacket",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/man jacket.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 5000,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 20,
      title: "pants",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/pants.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 500,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 20,
      title: "T-shirt",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/t-shirt.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 500,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),




];
final List<Product> shoes = [
  Product(
      quantity: 1,
      title: "Air Jordan",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/Air Jordan.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 700,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 1,
      title: "New Balance 990",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/New Balance 990.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 700,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 1,
      title: "Spots shoes",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/shoes.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 700,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 1,
      title: "New Sports shoes",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/sports shoes.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 700,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 1,
      title: "vans old school",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/vans old skool.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 700,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 1,
      title: "white sneaker",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/white sneaker.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 700,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 1,
      title: "women-shoes",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/women-shoes.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 700,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),




];
final List<Product> beauty = [
  Product(
      quantity: 1,
      title: "face care",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/face care.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 500,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 1,
      title: "Perfume",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/perfume.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 500,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 1,
      title: "face care",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/face care.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 500,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 1,
      title: "Perfume",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/perfume.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 500,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),




];
final List<Product> women = [
  Product(
      quantity: 1,
      title: "lengthen",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/lehenga.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 500,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 1,
      title: "kurta",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/kurta.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 500,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),




];
final List<Product> jewelry = [
  Product(
      quantity: 1,
      title: "jewelry-box",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/jewelry-box.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 5000,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 1,
      title: "jewelry",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/jewelry.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 500,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),




];
final List<Product> men = [
  Product(
      quantity:1,
      title: "man jacket",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/man jacket.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 5000,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 1,
      title: "pants",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/pants.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 500,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),
  Product(
      quantity: 1,
      title: "T-shirt",
      desc: "Lorem ispam memv lmdfv smdfnlkgnv dfnjjgnf",
      image: "images/t-shirt.png",
      review: "(800 reviews)",
      seller: "seller",
      price: 500,
      colors: [
        Colors.red,
        Colors.grey,
        Colors.green,
        Colors.white,
      ],
      category: "shoes",
      rate: 7.0),




];